"""
Even Fibonacci numbers

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four
million, find the sum of the even-valued terms.
"""

N = 4e6  # max fibonacci term size

a, b = 1, 2  # initial values
c = 0

even = [b]  # collect the fibonacci terms here

while c <= N:
    c = a + b
    a = b
    b = c

    if c <= N and (c % 2 == 0):
        even.append(c)

print(sum(even))
