from . import euler1
from . import euler2
from . import euler3
from . import euler4
from . import euler5
from . import euler6
from . import euler7
from . import euler8
from . import euler9
from . import euler10
from . import euler11
from . import euler12
from . import euler13
from . import euler14
from . import euler15
from . import euler16
from . import euler17
from . import euler18
from . import euler19
from . import euler20
from . import euler21
from . import euler22
from . import euler23
from . import euler24
from . import euler25
from . import euler26
from . import euler27
from . import euler28
from . import euler29
from . import euler30
from . import euler31
from . import euler32
from . import euler33
from . import euler34
from . import euler35
from . import euler36
from . import euler37
from . import euler38
from . import euler39
from . import euler40
from . import euler41
from . import euler42
from . import euler43
from . import euler44
